name: coder_status
description: An app to spark up the Competitive Programming strife among your peers.

publish_to: "none"
version: 1.0.0+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  firebase_core: ^1.13.1
  firebase_auth: ^3.3.11
  cloud_firestore: ^3.1.10
  fluttertoast: ^8.0.9
  image_picker: ^0.8.4+11
  image_cropper: ^1.5.0
  path: ^1.8.1
  firebase_storage: ^10.2.9
  http: ^0.13.4
  html: ^0.15.0
  rive: ^0.8.4
  flutter_phoenix: ^1.0.0
  rect_getter: ^1.1.0
  glassmorphism_ui: ^0.2.0
  dotted_border: ^2.0.0+2
  argon_buttons_flutter: ^1.1.0
  url_launcher: ^6.0.20
  font_awesome_flutter: ^9.2.0
  google_sign_in: ^5.2.4
  provider: ^6.0.2
  internet_connection_checker: ^0.0.1+3
  flutter_native_splash: ^2.1.1
  flutter_launcher_icons: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#141514"
  image: "images/appicon.png"

flutter_icons:
  android: true
  ios: true
  image_path: "images/appicon.png"

flutter:
  uses-material-design: true
  assets:
    - images/
    - assets/skeleton-place-holder.riv
    - assets/shine.riv
    - assets/cup.riv
    - assets/boy-scene.riv
    - assets/crown.riv
    - assets/no-peers.riv
    - assets/search-user.riv
    - assets/cup-crying.riv
  fonts:
    - family: Young
      fonts:
        - asset: fonts/young.ttf
    - family: Headline
      fonts:
        - asset: fonts/Headline.TTF
